---
pagetitle: "Cornelius Tanui | Projects"
title: "Projects"
---

### 1. [Quick Stats Reporter(QSR)](https://corneliuskiplimo.shinyapps.io/StatsReporter/)

This R Shiny web application is an extremely useful tool for quick data analysis and reporting. It determines on it's own what kind of table and graph to generate depending on the type of variable(s) selected.

### 2. [2019 KPHC Analytics](https://corneliuskiplimo.shinyapps.io/kenya_2019census/)

An R Shiny web dashboard application to demonstrate various findings of the 2019 Kenya Population and Housing Census. The app is auto-deployed using GitHub workflows and Docker CI/CD.

### 3. [miscellaneousR](https://github.com/corneliustanui/miscellaneousR)

This is an R package hosted on GitHub. The package contains convenient functions for performing simple to complex tasks appertaining to data wrangling.

### 4. [Fuzu Students Banding](https://corneliuskiplimo.shinyapps.io/FuzuStudentsBanding/)

A machine learning approach to household banding of university students in Kenya, powered by a multinomial regression model. The training data was ***simulated***, and as such the outcome does not reflect the reality. This [article](https://corneliustanui.rbind.io/content/posts/Simulation_2024-09-12/) covers the data simulation process.
